models:
  - model_id: meta-llama/Llama-3.2-3B-Instruct
    relation: base
    port: 8001
    gpu_factor: 1.3

  - model_id: RedHatAI/Qwen3-4B-Instruct-2507-quantized.w8a8
    relation: quantized
    port: 8002
    gpu_factor: 1.3

  #- model_id: RedHatAI/Qwen3-4B-Instruct-2507-quantized.w4a16
  #  relation: quantized
  #  port: 8003
  #  gpu_factor: 1.7

  #- model_id: meta-llama/Llama-3.2-3B-Instruct
  #  relation: independent
  #  port: 8004
  #  gpu_factor: 1.3

slo:
  accuracy: 0.9
  latency: 100
  weight_acc: 0.7
  weight_lat: 0.3

monitoring:
  sample_rate: 1
  sample_size: 15
  monotonicity: false
  discard: 2
  recycle: 0

scheduler:
  method: holt
  window: 10
