models:
  - model_id: meta-llama/Llama-3.1-8B-Instruct
    relation: base
    port: 8001
    gpu_factor: 1.3

  #- model_id: RedHatAI/Llama-3.2-3B-Instruct-quantized.w8a8
  #  relation: quantized
  #  port: 8002
  #  gpu_factor: 1.3

  #- model_id: Qwen/Qwen3-1.7B
  #  relation: independent
  #  port: 8003
  #  gpu_factor: 1.3

slo:
  accuracy: 0.95
  latency: 200
  weight_acc: 0.7
  weight_lat: 0.3


monitoring:
  sample_rate: 10
  sample_size: 50
  monotonicity: true
  discard: 3
  recycle: 3

scheduler:
  method: holt
  window: 10
