models:
  - name: A
    relation: base
    port: 8001
    model_id: meta-llama/Llama-3.1-8B-Instruct

  - name: B
    relation: quantized
    port: 8002
    model_id: espressor/meta-llama.Llama-3.2-3B-Instruct_W4A16

